### ISSUE TITLE
suggestion for using vars for lib paths

### ISSUE THREAD

**Issue by billspat** [cgross95/r-for-hpcc#1]
the material on package install is _really_ good and well paced.  I just have some suggestion for how to set R_LIBS_USER and using `.Renviron`. this is a version long-winded issue but I'm trying to understand how I would approach teaching this topic in addition to making suggestions for your material.   I've confused a lot of people on this topic so trying to get it right.  Sorry for the long read.  

here is the spot in your materials: 

https://github.com/cgross95/r-for-hpcc/blob/main/episodes/managing-r-env-packages.Rmd#L201

 I think  you should suggest setting it in `~/.bashrc`  R_LIBS_USER or better not at all, rather than  `.Renviron`

- per https://stat.ethz.ch/R-manual/R-devel/library/base/html/libPaths.html R_LIBS_USER is set automatically by R based on the version.   So a user doesn't really ever have to deal with that once it's created.   
> By default R_LIBS is unset, and if R_LIBS_USER is unset or empty, it is set to directory ‘R/R.version$platform-library/x.y’ of the home directory 
- given packages are associated with major R versions, if you create an R_LIBS_USER that is not versioned and upgrade say from R  3 to 4, packages are upgraded and you can't really go back to 3.  If you let it get set automatically, then you can use different versions of R and it will maintain different package folders for each version.  
-  you may want to set it if you may be using a path common to your whole lab (e.g. in /mnt/research) 
-  you want to maintain different libs for different projects, but there are other tools for that.  I use the package renv which is not easy to use but once you get the hang of it works well.   it's like virtualenv.   Packrat is anther tool but obsolete. 
-  When suggesting Renviron, I would mention that  if there is both a file in your home dire and a file in your project dir, the home dir one is never read, which can be confusing.    
-  Renviron is great for per-project (folder) config settings you don't want to put into code.    I'm not wording this well, but the idea is that if you want to use different lib_path for different projects, .Renviron is the one to use but if you use it in your project and then don't see R_LIBS_USER it will not read the one in the home dir.    Renviron is great for storing passwords/secrets in custom env variables and then using those in R code with `Sys.getenv` , and then put .Renviron in .gitignore.   but that may be a whole other topic on configuration.  I have a draft doc on that here: https://space-lab-msu.github.io/r_guide/configuration.html
-`~/.Rprofile` could also be used for this, but instead of Env vars it uses  R syntax and the link to the .lib_paths doc says how to set this.

**Comment by cgross95** [comment]
This is a super helpful critique. I was going mostly off of [Nanye's previous materials](https://docs.icer.msu.edu/R_workshop_tutorial/#r-startup) for this section, but your points add very helpful context.

I really appreciate the pointer to R's default user library setup. I remember having some confusion with this and wasn't sure where along the line it was set, so I tried to spoof a user not having that setup in the [Libraries](https://cgross95.github.io/r-for-hpcc/managing-r-env-packages.html#libraries) section.

I am wondering if I've addressed the use of `.Renviron` as a per-project configuration tool in the ["Mini package isolation solution"](https://cgross95.github.io/r-for-hpcc/managing-r-env-packages.html#a-mini-package-isolation-solution) exercise that actually carries through the rest of the workshop.

So in light of these points, here would be my changes:

- Streamline the discussion of `.libPaths()` in [Installing Packages](https://cgross95.github.io/r-for-hpcc/managing-r-env-packages.html#installing-packages) by removing the possibility of no default user library being set.
- Add clarification there that you should use different libraries for different R versions, so if you do mess with the libraries, make sure they don't cross over
-  Remove the [Managing your Environment](https://cgross95.github.io/r-for-hpcc/managing-r-env-packages.html#managing-your-environment) section that discusses a global `.Renviron` and `.Rprofile`.
- Add some further discussion about what you would want to add to your `.Renviron` file (secrets, API keys, data directories) in [Best Practices for Portable Projects](https://cgross95.github.io/r-for-hpcc/managing-r-env-packages.html#best-practices-for-a-portable-project-and-when-and-how-to-break-the-rules)

Let me know whether this would clarify things when you teach it, or if you'd prefer any other changes.

**Comment by cgross95** [comment]
Resolved by 917937cbdc9df10b05a2301b47b8656cd80f163b
