### ISSUE TITLE
describe capturing plots in cli/batch mode

### ISSUE THREAD

**Issue by billspat** [cgross95/r-for-hpcc#2]
Plots won't show when there is no graphic device, eg. using CLI in a term w/out X11 or in a batch job.   I don't see any examples with a plot in the lesson.   

We should add content to demonstrate how to use `pdf()` to capture plots.   I don't see any examples in the CLI section that do any plotting.  I will add this content to the CLI section and make a pull request.

**Comment by cgross95** [comment]
Ah, this is a good point! I will be unavailable to do any merging tomorrow morning until 10:30AM at the earliest, so I've added you as a collaborator. Feel free to commit as you see necessary.
