### ISSUE TITLE
suggestion: use parallel script for cli args challenge

### ISSUE THREAD

**Issue by billspat** [cgross95/r-for-hpcc#4]
*Content suggestion:*

In the CLI args section, the challenge (https://cgross95.github.io/r-for-hpcc/r-command-line.html#challenge3) is to write code that prints integers. 

Could this example instead build on the material from the parallel section, for which they should have an existing script?  (or have it as an additional challenge)

> Modify your Rscript `test_sqrt_multisession.R` to take an integer as a command line argument, and use that to set the number of iterations in the `foreach` loop?    How will the script handle when there is no parameter sent?

the solution would be something that includes

```r
num_reps = 10
if length(args > 0 ) { num_reps = strtoi(args[1]) }
x = 1:num_reps
```

controlling the number of reps for a simulation or model is something that scientists often need to do, so this may be close to real-world example.    but it may also be too many concepts at once.

**Comment by cgross95** [comment]
Resolved by https://github.com/MSU-ICER/r-for-hpcc/commit/a868cc7fd79af12f8cff129aeaf43da77d2db86f
