### ISSUE TITLE
suggestion : display alternate modules, link to module docs

### ISSUE THREAD

**Issue by billspat** [cgross95/r-for-hpcc#5]
Great instructions for loading R/4.0.3 from modules. 

I would add a link to the ICER docs: https://docs.icer.msu.edu/Intro_to_modules/

I have been using R/4.2.2 for spatial ecology and that also has many packages installed but more importantly also many system dependencies available.   For example this works well for spatial ecology

```
module purge
module load GCC/11.2.0  OpenMPI/4.1.1 GDAL R UDUNITS 
module load powertools
```

other modules are also available for GCC 11.2 that I've had to use with R including 

`module load automake XML-LibXML PostgreSQL libexif`

**Comment by cgross95** [comment]
Resolved by https://github.com/MSU-ICER/r-for-hpcc/commit/c5f2658b4cbf65f0dae0c7a6e4d57aacc408b31d
